### ISSUE TITLE
Can only submit form after changing a value

### ISSUE THREAD

**Issue by LvanAlphen** [formvalidation/formvalidation#1220]
I'm running into a problem where I can't submit a form with prefiled values. When i click submit all inputs are validated but the submit button is greyed out, see below:
![image](https://cloud.githubusercontent.com/assets/5519204/5265155/abff302e-7a40-11e4-96d7-6099317657e0.png)

I have to change a value off an input to reenable the submit button and then it does submit (even if i just paste in the same value is before)

Am i missing something here?

Regards,

Leo

**Comment by gruffvaughan** [comment]
Was this issue ever resolved? 

Every form I try to submit by AJAX has this issue where I enter text into an input, click submit, but the submit button greys out. I re-input the text, then when I click submit a second time, it processes.

Any ideas?

**Comment by nghuuphuoc** [comment]
@gruffvaughan 
It's fixed in the [latest code](https://github.com/formvalidation/formvalidation/archive/master.zip).
You can download the latest code and try again.

**Comment by gruffvaughan** [comment]
I’ve replaced my js and css files from the ‘dist’ folder of the download link you sent me, and I’m still having the same issue… Any ideas?

Thanks,
G

**Comment by nghuuphuoc** [comment]
@gruffvaughan 
Can you give me your HTML form markup and the JS you're calling?

**Comment by gruffvaughan** [comment]
I have several forms set up in the Wordpress admin area to be validated, using the following code for example:

```html

    <div class="function col-md-4">
		<form class="jg-function" action="" method="POST">
			<h3>Check if email is registered</h3>
			<div class="form-group">
				<label for="email">Email</label>
				<input type="email" class="form-control" name="email" placeholder="Email Address">
			</div>
			<input type="submit" class="button-primary submit" value="Check Email">
			<img src="<?php echo admin_url('/images/wpspin_light.gif'); ?>" class="loading" style="display:none;">
			<input type="hidden" name="action" value="account_checkEmail">
		</form>
		<div class="result"></div>
	</div>
```

```javascript

    var setFeedbackIcons = {
        valid: 'glyphicon glyphicon-ok',
        invalid: 'glyphicon glyphicon-remove',
        validating: 'glyphicon glyphicon-refresh'
    }

    var setValidationFields = {
    	email: {
	        validators: {
	            notEmpty: {
	                message: 'The email address is required and cannot be empty.'
	            },
	            emailAddress: {
	                message: 'The input is not a valid email address.'
	            }
	        }
	    }
    }

    $('form.jg-function').each(function() {
        $(this).formValidation({
            icon: setFeedbackIcons,
            fields: setValidationFields
        }).on('success.form.fv', function(e) {
            //Do things here
        }
    }
```

When submit is clicked, the button is disable, until I re-edit the input field, the button is enabled, and I can submit the form successfully.

Any ideas?

**Comment by nghuuphuoc** [comment]
@gruffvaughan
> When submit is clicked, the button is disable,

It's default and expected behaviour. The button will be disabled right after clicking on it to avoid double clicking.

What the behaviour you want to have in your case?

**Comment by gruffvaughan** [comment]
The button is disabled, but the form doesn’t submit. I have to edit a text field for the button to re-enable, and when I click the second time, it submits.

I’d obviously like the form to submit when I first click the submit button.

Any ideas?

G

**Comment by nghuuphuoc** [comment]
@gruffvaughan 
What do you do inside 
```javascript
.on('success.form.fv', function(e) {
    // Do things here
}
```

**Comment by gruffvaughan** [comment]
Quite a lot to be honest! Here's the code if you think it will help...

```javascript
$('form.jg-function').each(function() {

    	// Check if form needs to validate inputs (some functions are just simple button clicks!)
    	if (!$(this).find("input:not([type='submit'],[type=hidden])").length) {

    		$(this).submit( function() {
	        	var $form = $(this),
		        $formParent = $(this).parent(),
	        	$loading = $('.loading', this),
	        	$submit = $('.submit', this),
	        	$result = $('.result', $formParent),
	        	data = {},
				hidden = $('input[type=hidden]', this);

		        $loading.show();
				$submit.attr('disabled', true);

				$(hidden).each(function(){
	 				var input = $(this),
	 				inputName = input.attr("name"),
	 				inputValue = input.val();
	 				data[inputName] = input.val();
				});

				data['justgiving_nonce'] = justgiving_vars.justgiving_nonce;

				$.post(ajaxurl, data, function(response) {
					$result.html(response);
					$loading.hide();
					$submit.attr('disabled', false);
				});

		        return false;
		    });

    	} else {

    		$(this).formValidation({
		        icon: setFeedbackIcons,
		        fields: setValidationFields
		    }).on('success.form.fv', function(e) {
		        e.preventDefault();

		        $(this).submit( function() {
			       	var $form = $(this),
			        $formParent = $(this).parent(),
		        	$loading = $('.loading', this),
		        	$submit = $('.submit', this),
		        	$result = $('.result', $formParent),
		        	data = {},
					array1 = {},
					inputs = $('input, select, textarea', this).not(':input[type=submit]');

			        $loading.show();
					$submit.attr('disabled', true);

					$(inputs).each(function(){
		 				var input = $(this),
		 				inputName = input.attr("name"),
		 				inputValue = input.val(),
		 				split = {};
		 				
		 				if(inputName.indexOf('_') === -1) {
							data[inputName] = input.val();
						} else {
						   	split = inputName.split('_');

						   	first = split[0],
						   	second = split[1];
							
						   	if (first in data) {
						   		array1[second] = inputValue;
							} else {
								array1[second] = inputValue;
								data[first] = array1;
							}
						}
					});

					data['justgiving_nonce'] = justgiving_vars.justgiving_nonce;

					$.post(
                        ajaxurl,
                        data,
                        function(response) {
                            $submit.attr('disabled', false);
    						$loading.hide();
                            
                            /*******************************/
                            /* Search for Charity Function */
                            /*******************************/

                            if ($form.attr("id") == 'justgiving_search_charity') {

                                response = JSON.parse(response);
                                if (response.numberOfHits > 0) {
                                    $('#charity-search-result').prepend('<p>Your search for "'+response.query+'"" retrieved '+response.numberOfHits+' results. <a id="reset-charity-search" href="#">Search Again?</a>.</p>');
                                    $('#justgiving_search_charity').hide();

                                    var $dropdown = $("<select id=\"charity\" name=\"charity\" class=\"form-control\"/>").appendTo('#charity-search-result');
                                    $dropdown.append($("<option />").val('').text('- Choose A Result -'));

                                    $(response.charitySearchResults).each(function() {
                                        $dropdown.append($("<option />").val(this.charityId).text(this.name));
                                    });

                                    $('#charity').change(function(){
                                        var selected = $('#charity option:selected').val();

                                        if (selected) {
                                            charity = getCharity(response, selected);
                                            $('#charity-details').show();
                                            
                                            $('#charity-id').html('ID: '+charity["charityId"]);
                                            $('#charity-name').html('Name: '+charity["name"]);
                                            $('#charity-number').html('Registration Number: '+charity["registrationNumber"]);
                                            $('#charity-desc').html('Description: '+charity["description"]);
                                            $('#charity-img').attr("src",charity["logoUrl"]).attr("alt",charity["name"]);

                                            resetEventSearch();
                                            $('#justgiving_search_events_container').hide();
                                            $('#justgiving_search_events').show();
                                            $('#events-search-result').html('');

                                            // Set Event Search Form
                                            $('#justgiving_search_events input[name="q"]').val(charity["name"]);
                                            $('#justgiving_search_events_container').show();

                                            var formValidation = $('#justgiving_search_events').data('formValidation');
                                            formValidation.validateField('q');
                                        } else {
                                            resetCharitySearch();
                                            resetEventSearch();
                                            $('#justgiving_search_events_container').hide();
                                            $('#justgiving_search_events').show();
                                            $('#events-search-result').html('');
                                        }
                                    });
                                    $('#reset-charity-search').click( function(){
                                        $('#charity-search-result').html('').hide();
                                        $('#charity-details').hide();
                                        $('#justgiving_search_charity input[name="q"]').val(''); // Need to reset validator here.
                                        $('#justgiving_search_charity').show();
                                        return false;
                                    });
                                } else {
                                    $('#charity-search-result').prepend('<p>This charity has no upcoming events.</p>');
                                    $('#justgiving_search_charity').hide();
                                }

                            /*****************************/
                            /* Search for Event Function */
                            /*****************************/

                            } else if ( $form.attr("id") == 'justgiving_search_events' ) {

                                response = JSON.parse(response);

                                if (response.numberOfHits > 0) {
                                    $('#events-search-result').prepend('<p>Retrieved '+response.numberOfHits+' events.</p>');
                                    $('#justgiving_search_events').hide();

                                    var $dropdown = $("<select id=\"events\" name=\"events\" class=\"form-control\"/>").appendTo('#events-search-result');
                                    $dropdown.append($("<option />").val('').text('- Choose A Result -'));

                                    $(response.events).each(function() {
                                        $dropdown.append($("<option />").val(this.id).text(this.name));
                                    });

                                    $('#events').change(function(){
                                        var selected = $('#events option:selected').val();

                                        if (selected) {

                                            var events = getEvents(response, selected);
                                            
                                            $('#events-details').show();
                                            
                                            $('#event-id').html('ID: '+events["id"]);
                                            $('#event-name').html('Name: '+events["name"]);
                                            $('#event-location').html('Location: '+events["location"]);
                                            $('#event-startDate').html('Date: '+events["startDate"]);
                                            $('#event-amountRaised').html('Amount Raised: '+events["amountRaised"]);
                                            $('#event-amountGiftAid').html('Giftaid: '+events["amountGiftAid"]);
                                        } else {
                                            resetEventSearch();
                                        }
                                    });

                                } else {
                                    $('#event-search-result').prepend('<p>Your search for "'+response.query+'"" retrieved '+response.numberOfHits+' results. <a id="reset-charity-search" href="#">Search Again?</a>.</p>');
                                    $('#justgiving_search_events').hide();
                                }

                            /******************/
                            /* Account Create */
                            /******************/

                            } else if ( $form.attr("id") == 'justgiving_account_create' ) {

                                $form.hide();
                                $result.html(response);

                                $('#new-page').show();

                            /********************/
                            /* General Function */
                            /********************/

                            } else {
                                $form.hide();
                                $result.html(response);
                            }
				        }
                    );

			        return false;
			    });
			});
    	}
	});
```

**Comment by nghuuphuoc** [comment]
@gruffvaughan 
The form doesn't submit for the first time when the form is valid, because the ```success.form.fv``` doesn't do anything:

```javascript
$(form)
    .formValidation({
        ...
    })
    .on('success.form.fv', function(e) {
        e.preventDefault();
       
        // ---> This will not submit the form
        // It only handle the submit event, therefore 
        // it will be called in the next time the submit button is clicked
        $(this).submit(function() {
            // ... Do something
            return false;
        });
    });
```

In order to submit the form for the first time when ```success.form.fv``` is triggered, you need to call the [defaultSubmit()](http://formvalidation.io/api/#default-submit) method:

```javascript
$(form)
    .formValidation({
        ...
    })
    .on('success.form.fv', function(e) {
        e.preventDefault();
       
        $(this).submit(function() {
            // ... Do something
            return false;
        });

        // Submit the form
        $(form).formValidation('defaultSubmit');
    });
```

See the sample fiddle http://jsfiddle.net/nghuuphuoc/j2r85ryo/2/

**Comment by gruffvaughan** [comment]
Thanks for your help. infact, the problem is that for some bizarre reason I had decided to call the submit function inside the validation function.

Instead of:

```javascript

$(form)
    .formValidation({
        ...
    })
    .on('success.form.fv', function(e) {
        e.preventDefault();

        $(this).submit(function() {
            // ... Do something
            return false;
        });

        // Submit the form
        $(form).formValidation('defaultSubmit');
    });

```

I just needed this:

```javascript

$(form)
    .formValidation({
        ...
    })
    .on('success.form.fv', function(e) {
        e.preventDefault();

        // ... Do something

    });

```

All sorted! Apologies for the silly mistake.
